In [1]:
import pandas as pd 
import numpy as np
import joblib
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('../static/data/iris_train.csv')
df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.3                1.7               0.5   
1                6.1               3.0                4.9               1.8   
2                5.1               3.4                1.5               0.2   

   target  
0       0  
1       2  
2       0

In [3]:
df_test = pd.read_csv('../static/data/iris_train.csv')

In [4]:
# column값을 딕셔너리 형태로 저장, column_list는 키값만 저장
column_dict = {'sl':'Sepal length', 'sw':'Sepal width', 'pl':'Petal length', 'pw':'Petal width', 'species':['Setosa', 'Versicolor', 'Virginica']}
column_list = list(column_dict.keys())

In [5]:
# 딕셔너리
column_dict

{'sl': 'Sepal length',
 'sw': 'Sepal width',
 'pl': 'Petal length',
 'pw': 'Petal width',
 'species': ['Setosa', 'Versicolor', 'Virginica']}

In [6]:
# 딕셔너리의 key값
column_list

['sl', 'sw', 'pl', 'pw', 'species']

In [20]:
df.columns = column_list
df_test.columns = column_list

### Sepal-length, index=30

In [12]:
# 홈페이지에서 feature_name = sl, index=30을 선택한 경우
feature_name='sl'
index = 30

In [13]:
feature_name

'sl'

In [14]:
# 홈페이지에서 선택된 feature_name을 제외한 값을 X_train으로 사용할 예정, feature_name의 값을 X_test로 설정
X = df.drop(columns=feature_name, axis=1).values
y = df[feature_name].values

In [15]:
lr = LinearRegression()
lr.fit(X, y)
weight, bias = lr.coef_, lr.intercept_

In [16]:
weight, bias = lr.coef_, lr.intercept_

In [17]:
lr.coef_

array([ 0.62116981,  0.76805368, -0.44401781, -0.2649177 ])

In [18]:
lr.intercept_

1.879900015756494

In [21]:
# index로 지정한 숫자의 행 데이터를 X_test로 설정
X_test = df_test.drop(columns=feature_name, axis=1).values[index]
X_test

array([3.4, 5.6, 2.4, 2. ])

In [22]:
# X_test와 lr.coef_(weight)둘다 1x4행렬이므로 weight를 4x1행렬로 바꿔주고 회귀식을 완성 sl = lr.coef_[0].T*X_test[0] + lr.coef_[1].T*X_test[1] + lr.coef_[2].T*X_test[2] + lr.coef_[3].T*X_test[3] + bias 로 회귀식 완성
pred_value = np.dot(X_test, weight.T) + bias

In [23]:
df_test.iloc[index,:-1].values

array([6.3, 3.4, 5.6, 2.4])

In [24]:
x_test = list(df_test.iloc[index,:-1].values)
x_test

[6.3, 3.4, 5.6, 2.4]

In [25]:
column_dict['species']

['Setosa', 'Versicolor', 'Virginica']

In [26]:
# target값
int(df_test.iloc[index,-1])

2

In [27]:
x_test.append(column_dict['species'][int(df_test.iloc[index,-1])])

In [28]:
x_test

[6.3, 3.4, 5.6, 2.4, 'Virginica']

In [29]:
# x_test의 값을 딕셔너리 형태로 변경
org = dict(zip(column_list, x_test))

In [30]:
org

{'sl': 6.3, 'sw': 3.4, 'pl': 5.6, 'pw': 2.4, 'species': 'Virginica'}

In [42]:
# 일단 0으로 만들어 준다.
pred = dict(zip(column_list[:-1], [0,0,0,0]))

In [43]:
pred

{'sl': 0, 'sw': 0, 'pl': 0, 'pw': 0}

In [46]:
# 0으로 설정된 pred값에 pred_value구해놓은 값을 소수점 첫째 자리까지 설정하여 구한다.
pred[feature_name] = np.round(pred_value, 2)

In [47]:
pred[feature_name]

6.7